### ISSUE TITLE
使用中发现的几个小问题

### ISSUE THREAD

**Issue by samzhangjy** [loopyme/safeSearch#1]
首先，我非常喜欢这个项目，能够让人们快速的寻找所需要的资料，并以时间排序。我在使用中发现了几个小问题，望修复。

## 环境
**操作系统**：macOS 14
**Python版本**：v3.6

### 其它
**是否使用了虚拟环境**：是，virtualenv。

## 问题描述
- 在使用中，运行就会报错`ModuleNotFoundError: No module named 'safeSearch'`，在引用之前添加
  ```python
  import sys, os
  sys.path.append(os.path.abspath('./src'))
  ```
  就可以正常运行了。

- 在解决上述问题后，又会报错`ModuleNotFoundError: No module named 'yaml'`，安装PyYAML后即可正常运行，但`requirements.txt`中没有该库。

感谢！

**Comment by loopyme** [comment]
感谢反馈！

关于提出的问题：
 - **import失败**：目前还没有打包成package，要运行的话需要手动配置。我认为配置路径实际上是个客户端的问题，仓库里将暂时不做修复，后面有空补个`setup.py`。
 - **requirements没写全**：偷懒手打requirements的时候忘了，感谢提醒，稍后补上。
